import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

// Переводы интерфейса
const translations = {
    ru: {
        home: "Главная",
        categories: "Категории",
        places: "Места",
        tours: "Туры",
        back: "Назад",
        loading: "Загрузка...",
        error: "Ошибка загрузки",
        noData: "Нет данных",
        settings: "Настройки",
        language: "Язык",
        theme: "Тема",
        fontSize: "Размер шрифта",
        save: "Сохранить",
        cancel: "Отмена",
        explore: "Туризм в Мангистау",
        selectCategory: "Выберите категорию для просмотра мест",
        details: "Подробнее",
        search: "Поиск мест",
        searchPlaceholder: "Введите название места или описание...",
        searchResults: "Результаты поиска",
        noSearchResults: "Ничего не найдено по вашему запросу",
        featuredPlaces: "Рекомендуемые места",
        previous: "Предыдущее",
        next: "Следующее",
        slide: "Слайд",
        map: "Карта",
        placesOnMap: "Мест на карте",
        showOnMap: "Показать на карте",
        showAllPlaces: "Показать все места",
        settingsSaved: "Настройки сохранены",
        Move: "Открыть",
        legends: "Легенды",
        price: "Цена",
        company: "Компания",
        services: "Услуги",
        contact: "Контакты",
        moreDetails: "Подробнее",
        tourDetails: "О туре",
        backToTours: "Вернуться к турам",
        placesInThisTour: "Места в этом туре",
        availableTours: "Доступные туры",
        noTours: "Нет доступных туров",
        noToursForThisPlace: "Для этого места нет доступных туров",
        errorLoadingTours: "Ошибка загрузки туров",
        retry: "Повторить",
        noImage: "Нет изображения",
        about: "О нас",
        phone: "Телефон",
        instagram: "Инстаграм",
        aboutDescription:
            "Apex Tourism — это ваш проводник в изучении великолепного региона Мангистау. Наше приложение разработано, чтобы помочь путешественникам открывать для себя уникальные природные и культурные достопримечательности этой прекрасной области Казахстана.",
        ourMission: "Наша миссия",
        missionDescription:
            "Мы стремимся способствовать устойчивому туризму в Мангистау, предоставляя подробную информацию о местных достопримечательностях, повышая осведомленность о богатом культурном наследии региона и поддерживая местные предприятия и туроператоров.",
        whatWeOffer: "Что мы предлагаем",
        offer1: "Полная база данных туристических достопримечательностей Мангистау",
        offer2: "Подробная информация о каждом месте, включая историю, легенды и фотографии",
        offer3: "Интерактивная карта, которая поможет вам ориентироваться и исследовать регион",
        offer4: "Подобранные туры, созданные местными экспертами",
        offer5: "Информация о местной культуре, традициях и обычаях",
        offer6: "Отзывы пользователей и рейтинги, которые помогут вам принимать обоснованные решения",
        whyChooseUs: "Почему выбирают Apex Tourism?",
        whyChooseUsDescription:
            "Наша команда сочетает местную экспертизу с современными технологиями, чтобы обеспечить вам лучший возможный туристический опыт. Мы работаем напрямую с местными гидами и туроператорами, чтобы предоставить подлинные и незабываемые впечатления для наших посетителей.",
        trustedCompanion: "Ваш надежный туристический компаньон в Мангистау",
        // Company page translations
        companyAbout:
            "Mangystau Tour — это туристическая компания, специализирующаяся на организации путешествий по Мангистау. Мы показываем уникальную природу, исторические и культурные памятники региона, делая отдых ярким и незабываемым.",
        companyFounded: "Основано в 2015 году",
        companyAddress: "г. Актау, ул. Достык, 45",
        companyServices: [
            "Туры по Мангистау",
            "Экскурсии к Шерқала, Бозжыра, Тузбаир",
            "Сафари по степи",
            "Кемпинг и активный отдых",
        ],
        // Authentication translations
        profile: "Профиль",
        login: "Вход",
        signup: "Регистрация",
        email: "Email",
        password: "Пароль",
        fullName: "Полное имя",
        enterEmail: "Введите ваш email",
        enterPassword: "Введите ваш пароль",
        enterFullName: "Введите ваше полное имя",
        signIn: "Войти",
        signUp: "Зарегистрироваться",
        signOut: "Выйти",
        noAccount: "Нет аккаунта?",
        haveAccount: "Уже есть аккаунт?",
        register: "Зарегистрироваться",
        loginAction: "Войти",
        profileUpdated: "Профиль успешно обновлен",
        errorLoadingProfile: "Ошибка при загрузке профиля",
        saveChanges: "Сохранить изменения",
        saving: "Сохранение...",
        signingOut: "Выход...",
        checkEmail:
            "Пожалуйста, проверьте вашу почту и подтвердите адрес электронной почты.",
        fillAllFields: "Пожалуйста, заполните все поля",
        passwordMinLength: "Пароль должен содержать минимум 6 символов",
        signupSuccess:
            "Регистрация успешна! Проверьте ваш email для подтверждения.",
        confirmPassword: "Подтвердите пароль",
        enterPasswordAgain: "Введите пароль еще раз",
        // Application name
        appName: "Apex Tourism",
        // Instagram
        visitInstagram: "Посетить Instagram",
        // 360° view
        view360: "360° Просмотр",
        view360NotAvailable: "Пока недоступно",
        // Chat translations
        aiAssistant: "Ассистент",
        queuePending: "Очередь:",
        closeChat: "Закрыть чат",
        typeMessage: "Введите ваше сообщение...",
        sendMessage: "Отправить сообщение",
        send: "Отправить",
        chatError:
            "Извините, произошла ошибка. Пожалуйста, попробуйте еще раз.",
        chatWelcomeMessage:
            "Привет! Я ваш туристический гид по Мангистау. Задавайте вопросы о достопримечательностях, маршрутах и культуре региона.",
        copyMessage: "Копировать сообщение",
        regenerateMessage: "Перегенерировать сообщение",
        rateMessage: "Оценить сообщение",
        chatSessions: "История чатов",
        newChat: "Новый чат",
        offline: "Офлайн",
        offlineMessage: "Нет подключения к интернету",
        chatHint: "Нажмите Ctrl+Enter для отправки",
        suggestQuestion1: "Расскажи о достопримечательностях Мангистау",
        suggestQuestion2: "Какие туры доступны?",
        suggestQuestion3: "Покажи интересные места на карте",
        basicSettings: "Основные настройки",
        // Language names
        languageRussian: "Русский",
        languageEnglish: "English",
        languageKazakh: "Қазақша",
        // Theme names
        themeLight: "Светлая",
        themeDark: "Тёмная",
        // Font sizes
        fontSizeSmall: "Маленький",
        fontSizeNormal: "Обычный",
        fontSizeLarge: "Крупный",
        fontSizeExtraLarge: "Очень крупный",
        // Feedback translations
        visitorReviews: "Отзывы посетителей",
        averageRating: "Средняя оценка",
        reviews: "Отзывов",
        leaveReview: "Оставить отзыв",
        yourRating: "Ваша оценка:",
        yourComment: "Ваш комментарий:",
        shareExperience: "Поделитесь своими впечатлениями...",
        submitReview: "Отправить отзыв",
        submitting: "Отправка...",
        pleaseLoginToReview:
            "Пожалуйста, войдите в систему, чтобы оставить отзыв",
        pleaseRate: "Пожалуйста, поставьте оценку",
        reviewError: "Ошибка при отправке отзыва:",
        loadingReviews: "Загрузка отзывов...",
        errorLoadingReviews: "Ошибка загрузки отзывов:",
        noReviewsYet: "Пока нет отзывов. Будьте первым!",
        anonymousUser: "Анонимный пользователь",
        pleaseLoginOrSignup:
            "Пожалуйста, войдите или зарегистрируйтесь, чтобы пользоваться чат-ботом.",
        loginLink: "Войдите",
        signupLink: "Зарегистрируйтесь",
        // Articles page translations
        articles: "Статьи",
        articlesHeroTitle: "Откройте для себя Мангистауский край",
        articlesHeroDescription:
            "Читайте свежие материалы о культуре, природе и людях Мангистау",
        articlesDescription:
            "Откройте для себя интересные истории, советы и путеводители по Мангистау",
        allCategories: "Все категории",
        noArticles: "Статьи не найдены",
        articleNotFound: "Статья не найдена",
        backToArticles: "Вернуться к статьям",
        minRead: "мин чтения",
        views: "просмотров",
        gallery: "Галерея",
        similarArticles: "Похожие статьи",
        min: "мин",
        readMore: "Читать далее",
        exploreArticles: "Перейти к статьям",
        articlesCallToAction: "Узнайте больше о Мангистау из наших статей",
        exploreMusic: "Слушать музыку",
        musicHeroTitle: "Музыка Мангистау",
        musicHeroDescription: "Послушайте традиционные кюй и мелодии региона",
        music: "Музыка",
        composer: "Композитор",
        duration: "Длительность",
        listenNow: "Слушать",
        noMusic: "Композиций не найдено",
        showDescription: "Показать описание",
        hideDescription: "Скрыть описание",
        download: "Скачать",
        playbackSpeed: "Скорость воспроизведения",
    },
    en: {
        home: "Home",
        categories: "Categories",
        places: "Places",
        tours: "Tours",
        back: "Back",
        loading: "Loading...",
        error: "Loading Error",
        noData: "No Data",
        settings: "Settings",
        language: "Language",
        theme: "Theme",
        fontSize: "Font Size",
        save: "Save",
        cancel: "Cancel",
        explore: "Tourism in Mangystau",
        selectCategory: "Select a Category to View Places",
        details: "Details",
        search: "Search Places",
        searchPlaceholder: "Enter place name or description...",
        searchResults: "Search Results",
        noSearchResults: "Nothing Found for Your Request",
        featuredPlaces: "Featured Places",
        previous: "Previous",
        next: "Next",
        slide: "Slide",
        map: "Map",
        placesOnMap: "Places on Map",
        showOnMap: "Show on Map",
        showAllPlaces: "Show All Places",
        settingsSaved: "Settings Saved",
        Move: "Open",
        legends: "Legends",
        price: "Price",
        company: "Company",
        services: "Services",
        contact: "Contact",
        moreDetails: "More Details",
        tourDetails: "Tour Details",
        backToTours: "Back to Tours",
        placesInThisTour: "Places in This Tour",
        availableTours: "Available Tours",
        noTours: "No Tours Available",
        noToursForThisPlace: "No Tours Available for This Place",
        errorLoadingTours: "Error Loading Tours",
        retry: "Retry",
        noImage: "No Image",
        about: "About Us",
        phone: "Phone",
        instagram: "Instagram",
        aboutDescription:
            "Apex Tourism is your gateway to exploring the magnificent Mangystau region. Our application is designed to help travelers discover the unique natural and cultural attractions of this beautiful area in Kazakhstan.",
        ourMission: "Our Mission",
        missionDescription:
            "We aim to promote sustainable tourism in Mangystau by providing detailed information about local attractions, creating awareness about the region's rich cultural heritage, and supporting local businesses and tour operators.",
        whatWeOffer: "What We Offer",
        offer1: "Comprehensive database of tourist attractions in Mangystau",
        offer2: "Detailed information about each location including history, legends, and photos",
        offer3: "Interactive map to help you navigate and explore the region",
        offer4: "Curated tours created by local experts",
        offer5: "Information about local culture, traditions, and customs",
        offer6: "User reviews and ratings to help you make informed decisions",
        whyChooseUs: "Why Choose Apex Tourism?",
        whyChooseUsDescription:
            "Our team combines local expertise with modern technology to provide you with the best possible travel experience. We work directly with local guides and tour operators to ensure authentic and memorable experiences for our visitors.",
        trustedCompanion: "Your Trusted Travel Companion in Mangystau",
        // Company page translations
        companyAbout:
            "Mangystau Tour is a travel company specializing in organizing trips across Mangystau. We showcase the region's unique nature, historical and cultural landmarks, making your journey bright and unforgettable.",
        companyFounded: "Founded in 2015",
        companyAddress: "Aktau, Dostyk St., 45",
        companyServices: [
            "Mangystau Tours",
            "Excursions to Sherkala, Bozzhyra, Tuzbair",
            "Steppe Safari",
            "Camping and Outdoor Activities",
        ],
        // Authentication translations
        profile: "Profile",
        login: "Login",
        signup: "Sign Up",
        email: "Email",
        password: "Password",
        fullName: "Full Name",
        enterEmail: "Enter Your Email",
        enterPassword: "Enter Your Password",
        enterFullName: "Enter Your Full Name",
        signIn: "Sign In",
        signUp: "Sign Up",
        signOut: "Sign Out",
        noAccount: "No Account?",
        haveAccount: "Already Have an Account?",
        register: "Register",
        loginAction: "Log In",
        profileUpdated: "Profile Updated Successfully",
        errorLoadingProfile: "Error Loading Profile",
        saveChanges: "Save Changes",
        saving: "Saving...",
        signingOut: "Signing Out...",
        checkEmail: "Please Check Your Email and Confirm Your Email Address.",
        fillAllFields: "Please Fill in All Fields",
        passwordMinLength: "Password Must Be at Least 6 Characters",
        signupSuccess:
            "Registration Successful! Please Check Your Email for Confirmation.",
        confirmPassword: "Confirm Password",
        enterPasswordAgain: "Enter Password Again",
        // Application name
        appName: "Apex Tourism",
        // Instagram
        visitInstagram: "Visit Instagram",
        // 360° view
        view360: "360° View",
        view360NotAvailable: "Not Available Yet",
        // Chat translations
        aiAssistant: "Assistant",
        queuePending: "Queue:",
        closeChat: "Close Chat",
        typeMessage: "Type Your Message...",
        sendMessage: "Send Message",
        send: "Send",
        chatError: "Sorry, I Encountered an Error. Please Try Again.",
        chatWelcomeMessage:
            "Hello! I'm Your Tourism Guide for Mangystau. Ask Questions About Attractions, Routes, and Regional Culture.",
        copyMessage: "Copy Message",
        regenerateMessage: "Regenerate Message",
        rateMessage: "Rate Message",
        chatSessions: "Chat History",
        newChat: "New Chat",
        offline: "Offline",
        offlineMessage: "No Internet Connection",
        chatHint: "Press Ctrl+Enter to Send",
        suggestQuestion1: "Tell Me About Mangystau Attractions",
        suggestQuestion2: "What Tours Are Available?",
        suggestQuestion3: "Show Interesting Places on the Map",
        basicSettings: "Basic Settings",
        // Language names
        languageRussian: "Русский",
        languageEnglish: "English",
        languageKazakh: "Қазақша",
        // Theme names
        themeLight: "Light",
        themeDark: "Dark",
        // Font sizes
        fontSizeSmall: "Small",
        fontSizeNormal: "Normal",
        fontSizeLarge: "Large",
        fontSizeExtraLarge: "Extra Large",
        // Feedback translations
        visitorReviews: "Visitor Reviews",
        averageRating: "Average Rating",
        reviews: "Reviews",
        leaveReview: "Leave a Review",
        yourRating: "Your Rating:",
        yourComment: "Your Comment:",
        shareExperience: "Share Your Experience...",
        submitReview: "Submit Review",
        submitting: "Submitting...",
        pleaseLoginToReview: "Please Log in to Leave a Review",
        pleaseRate: "Please Provide a Rating",
        reviewError: "Error Submitting Review:",
        loadingReviews: "Loading Reviews...",
        errorLoadingReviews: "Error Loading Reviews:",
        noReviewsYet: "No Reviews Yet. Be the First!",
        anonymousUser: "Anonymous User",
        pleaseLoginOrSignup: "Please Log in or Sign up to use the chatbot.",
        loginLink: "Log In",
        signupLink: "Sign Up",
        // Articles page translations
        articles: "Articles",
        articlesHeroTitle: "Discover the Mangystau Region",
        articlesHeroDescription:
            "Read fresh stories about the culture, nature and people of Mangystau",
        articlesDescription:
            "Discover interesting stories, tips and guides about Mangystau",
        allCategories: "All Categories",
        noArticles: "No articles found",
        articleNotFound: "Article not found",
        backToArticles: "Back to Articles",
        minRead: "min read",
        views: "views",
        gallery: "Gallery",
        similarArticles: "Similar Articles",
        min: "min",
        readMore: "Read More",
        exploreArticles: "Explore Articles",
        articlesCallToAction: "Learn more about Mangystau from our articles",
        exploreMusic: "Explore Music",
        musicHeroTitle: "Mangystau Music",
        musicHeroDescription:
            "Listen to traditional kuy and melodies of the region",
        music: "Music",
        composer: "Composer",
        duration: "Duration",
        listenNow: "Listen",
        noMusic: "No music found",
        showDescription: "Show description",
        hideDescription: "Hide description",
        download: "Download",
        playbackSpeed: "Playback Speed",
    },
    kz: {
        home: "Басты бет",
        categories: "Санаттар",
        places: "Орындар",
        tours: "Турлар",
        back: "Артқа",
        loading: "Жүктелуде...",
        error: "Жүктеу қатесі",
        noData: "Деректер жоқ",
        settings: "Баптаулар",
        language: "Тіл",
        theme: "Тақырып",
        fontSize: "Қаріп өлшемі",
        save: "Сақтау",
        cancel: "Болдырмау",
        explore: "Маңғыстаудағы туризм",
        selectCategory: "Орындарды көру үшін санатты таңдаңыз",
        details: "Толығырақ",
        search: "Орындарды іздеу",
        searchPlaceholder: "Орын атауын немесе сипаттамасын енгізіңіз...",
        searchResults: "Іздеу нәтижелері",
        noSearchResults: "Сұрауыңыз бойынша ештеңе табылмады",
        featuredPlaces: "Ұсынылатын орындар",
        previous: "Алдыңғы",
        next: "Келесі",
        slide: "Слайд",
        map: "Карта",
        placesOnMap: "Картадағы орындар",
        showOnMap: "Картада көрсету",
        showAllPlaces: "Барлық орындарды көрсету",
        settingsSaved: "Баптаулар сақталды",
        Move: "Ашу",
        legends: "Аңыздар",
        price: "Бағасы",
        company: "Компания",
        services: "Қызметтер",
        contact: "Байланыс",
        moreDetails: "Толығырақ",
        tourDetails: "Тур туралы",
        backToTours: "Турларға қайту",
        placesInThisTour: "Осы турдағы орындар",
        availableTours: "Қолжетімді турлар",
        noTours: "Қолжетімді турлар жоқ",
        noToursForThisPlace: "Осы орын үшін қолжетімді турлар жоқ",
        errorLoadingTours: "Турларды жүктеу қатесі",
        retry: "Қайталау",
        noImage: "Сурет жоқ",
        about: "Біз туралы",
        phone: "Телефон",
        instagram: "Instagram",
        aboutDescription:
            "Apex Tourism — Маңғыстау өңірін зерттеуге арналған негізгі қақпаңыз. Біздің қолданба саяхатшыларға Қазақстанның осы ғажайып аймағының бірегей табиғи және мәдени көрнекті жерлерін ашуға көмектеседі.",
        ourMission: "Біздің миссиямыз",
        missionDescription:
            "Біз Маңғыстауда тұрақты туризмді насихаттау мақсатында жергілікті көрнекті жерлер туралы егжей-тегжейлі ақпарат беру, өңірдің бай мәдени мұрасы туралы хабардарлықты арттыру және жергілікті кәсіпкерлер мен туроператорларға қолдау көрсету мақсатында жұмыс істейміз.",
        whatWeOffer: "Біз ұсынатын мүмкіндіктер",
        offer1: "Маңғыстаудағы туристік көрнекті жерлердің толық дерекқоры",
        offer2: "Әрбір орынның тарихы, аңыздары және фотосуреттері туралы егжей-тегжейлі ақпарат",
        offer3: "Өңірде бағдарлауға және зерттеуге көмектесетін интерактивті карта",
        offer4: "Жергілікті мамандар жасаған таңдаулы турлар",
        offer5: "Жергілікті мәдениет, дәстүрлер және әдет-ғұрыптар туралы ақпарат",
        offer6: "Шешім қабылдауға көмектесетін пайдаланушы пікірлері мен рейтингтері",
        whyChooseUs: "Неліктен Apex Tourism таңдау керек?",
        whyChooseUsDescription:
            "Біздің команда жергілікті тәжірибені заманауи технологиялармен ұштастырып, сізге ең жақсы саяхат тәжірибесін ұсынады. Біз жергілікті гидтар мен туроператорлармен тікелей жұмыс істеп, қонақтарымыз үшін шынайы және есте қаларлық тәжірибелерді қамтамасыз етеміз.",
        trustedCompanion: "Маңғыстаудағы сенімді саяхат серігіңіз",
        // Company page translations
        companyAbout:
            "Mangystau Tour — Маңғыстау бойынша сапарларды ұйымдастыруға маманданған туристік компания. Біз аймақтың ерекше табиғатын, тарихи және мәдени орындарын көрсетеміз, демалысты жарқын әрі есте қаларлық етеміз.",
        companyFounded: "2015 жылы құрылған",
        companyAddress: "Ақтау қ., Достық көш., 45",
        companyServices: [
            "Маңғыстау турлары",
            "Шерқала, Бозжыра, Тұзбайыр экскурсиялары",
            "Дала сафарисі",
            "Кемпинг және белсенді демалыс",
        ],
        // Authentication translations
        profile: "Профиль",
        login: "Кіру",
        signup: "Тіркелу",
        email: "Email",
        password: "Құпия сөз",
        fullName: "Толық аты",
        enterEmail: "Email енгізіңіз",
        enterPassword: "Құпия сөзді енгізіңіз",
        enterFullName: "Толық атыңызды енгізіңіз",
        signIn: "Кіру",
        signUp: "Тіркелу",
        signOut: "Шығу",
        noAccount: "Тіркелгі жоқ па?",
        haveAccount: "Тіркелгіңіз бар ма?",
        register: "Тіркелу",
        loginAction: "Кіру",
        profileUpdated: "Профиль сәтті жаңартылды",
        errorLoadingProfile: "Профильді жүктеу қатесі",
        saveChanges: "Өзгерістерді сақтау",
        saving: "Сақталуда...",
        signingOut: "Шығу...",
        checkEmail: "Электрондық поштаңызды тексеріп, мекенжайыңызды растаңыз.",
        fillAllFields: "Барлық өрістерді толтырыңыз",
        passwordMinLength: "Құпия сөз кемінде 6 таңбадан тұруы керек",
        signupSuccess:
            "Тіркеу сәтті өтті! Растау үшін электрондық поштаңызды тексеріңіз.",
        confirmPassword: "Құпия сөзді растау",
        enterPasswordAgain: "Құпия сөзді қайта енгізіңіз",
        // Application name
        appName: "Apex Tourism",
        // Instagram
        visitInstagram: "Instagram-ға өту",
        // 360° view
        view360: "360° Көрініс",
        view360NotAvailable: "Әзірше қолжетімді емес",
        // Chat translations
        aiAssistant: "Ассистент",
        queuePending: "Кезек:",
        closeChat: "Чатты жабу",
        typeMessage: "Хабарламаңызды теріңіз...",
        sendMessage: "Хабарлама жіберу",
        send: "Жіберу",
        chatError: "Кешіріңіз, қате орын алды. Қайтадан көріңіз.",
        chatWelcomeMessage:
            "Сәлем! Мен Маңғыстау өңірінің туризм гидімін. Көрнекті жерлер, маршруттар және өңір мәдениеті туралы сұрақтар қойыңыз.",
        copyMessage: "Хабарламаны көшіру",
        regenerateMessage: "Хабарламаны қайта жасау",
        rateMessage: "Хабарламаны бағалау",
        chatSessions: "Чат тарихы",
        newChat: "Жаңа чат",
        offline: "Офлайн",
        offlineMessage: "Интернет байланысы жоқ",
        chatHint: "Жіберу үшін Ctrl+Enter басыңыз",
        suggestQuestion1: "Маңғыстау көрнекті жерлері туралы айтып бер",
        suggestQuestion2: "Қандай турлар бар?",
        suggestQuestion3: "Картада қызықты жерлерді көрсет",
        basicSettings: "Негізгі баптаулар",
        // Language names
        languageRussian: "Русский",
        languageEnglish: "English",
        languageKazakh: "Қазақша",
        // Theme names
        themeLight: "Жарық",
        themeDark: "Қараңғы",
        // Font sizes
        fontSizeSmall: "Кіші",
        fontSizeNormal: "Қалыпты",
        fontSizeLarge: "Үлкен",
        fontSizeExtraLarge: "Өте үлкен",
        // Feedback translations
        visitorReviews: "Қонақтардың пікірлері",
        averageRating: "Орташа бағалау",
        reviews: "Пікір",
        leaveReview: "Пікір қалдыру",
        yourRating: "Сіздің бағалауыңыз:",
        yourComment: "Сіздің пікіріңіз:",
        shareExperience: "Өз тәжірибеңізбен бөлісіңіз...",
        submitReview: "Пікір жіберу",
        submitting: "Жіберілуде...",
        pleaseLoginToReview: "Пікір қалдыру үшін жүйеге кіріңіз",
        pleaseRate: "Бағалау қалдырыңыз",
        reviewError: "Пікір жіберу қатесі:",
        loadingReviews: "Пікірлер жүктелуде...",
        errorLoadingReviews: "Пікірлерді жүктеу қатесі:",
        noReviewsYet: "Әлі пікірлер жоқ. Бірінші болыңыз!",
        anonymousUser: "Анонимді пайдаланушы",
        pleaseLoginOrSignup: "Чат-ботты пайдалану үшін кіріңіз немесе тіркеліңіз.",
        loginLink: "Кіріңіз",
        signupLink: "Тіркеліңіз",
        // Articles page translations
        articles: "Мақалалар",
        articlesHeroTitle: "Маңғыстау өңірін ашыңыз",
        articlesHeroDescription:
            "Маңғыстаудың мәдениеті, табиғаты және адамдары туралы жаңа материалдарды оқыңыз",
        articlesDescription:
            "Маңғыстау туралы қызықты әңгімелер, кеңестер және гидтерді табыңыз",
        allCategories: "Барлық санаттар",
        noArticles: "Мақалалар табылмады",
        articleNotFound: "Мақала табылмады",
        backToArticles: "Мақалаларға оралу",
        minRead: "мин оқу",
        views: "көрулер",
        gallery: "Галерея",
        similarArticles: "Ұқсас мақалалар",
        min: "мин",
        readMore: "Толығырақ",
        exploreArticles: "Мақалаларға өту",
        articlesCallToAction:
            "Біздің мақалалардан Маңғыстау туралы көбірек біліңіз",
        exploreMusic: "Музыканы тыңдау",
        musicHeroTitle: "Маңғыстау музыкасы",
        musicHeroDescription: "Өңірдің дәстүрлі күйлері мен әуендерін тыңдаңыз",
        music: "Музыка",
        composer: "Композитор",
        duration: "Ұзақтығы",
        listenNow: "Тыңдау",
        noMusic: "Музыка табылмады",
        showDescription: "Сипаттаманы көрсету",
        hideDescription: "Сипаттаманы жасыру",
        download: "Жүктеп алу",
        playbackSpeed: "Ойнату жылдамдығы",
    },
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState("ru");

    useEffect(() => {
        const savedLanguage = localStorage.getItem("app_language") || "ru";
        setLanguage(savedLanguage);
    }, []);

    const changeLanguage = (newLanguage) => {
        setLanguage(newLanguage);
        localStorage.setItem("app_language", newLanguage);
    };

    const t = (key) => translations[language][key] || key;

    // Функция для получения названия поля в зависимости от языка
    const getLocalizedField = (obj, fieldName) => {
        if (!obj) return "";
        const localizedField = `${fieldName}_${language}`;
        return (
            obj[localizedField] ||
            obj[`${fieldName}_ru`] ||
            obj[`${fieldName}_en`] ||
            obj[`${fieldName}_kz`] ||
            ""
        );
    };

    const value = {
        language,
        changeLanguage,
        t,
        getLocalizedField,
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
